require "jogi.options"
require "jogi.plugins"
require "jogi.colorscheme"
require "jogi.keymaps"
require "jogi.lsp"
require "jogi.dap"
require "jogi.snip"
require "jogi.neotree"
require "jogi.misc"

--require "jogi.vimspector"
