
require "user.autopairs"
require "user.bufferline"
require "user.cmp"
require "user.colorscheme"
require "user.comment"
require "user.gitsigns"
require "user.keymaps"
require "user.lsp"
require "user.nvimtree"
require "user.options"
require "user.plugins"
require "user.telescope"
require "user.treesitter"
--require "user.vimspector"
require "user.dap"
require "user.lualine"
